In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [19]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
Min_Max = preprocessing.MinMaxScaler()
Ordinal =preprocessing.OrdinalEncoder()


def one_hot_cols(df,cols_to_one):
    one_hot=pd.get_dummies(df,cols_to_one,columns=cols_to_one)
    return one_hot


def fit_cols(df, cols_to_fit,fit_function ):
    for col in cols_to_fit:
        df[col] = pd.DataFrame(fit_function.fit_transform(pd.DataFrame(df[col])),columns=[col])
    return df


def split_Dataset(mypandas, cols_for_Y,size=0.2,state=1):
    
    X =  mypandas.drop(cols_for_Y, axis=1)
    Y = mypandas[cols_for_Y]
    X.head()
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=size, random_state=state)
    return X_train.to_numpy(), X_test.to_numpy(), Y_train.to_numpy(), Y_test.to_numpy()


import matplotlib.pyplot as plt


def Show_History(History):
    # summarize history for accuracy
    plt.plot(History.history['accuracy'])
    plt.plot(History.history['val_accuracy'])
    plt.title('model accuracy')
    plt.ylabel('accuracy')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()
    # summarize history for loss
    plt.plot(History.history['loss'])
    plt.plot(History.history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()

In [20]:
dataset = pd.read_csv('datasets/iris.csv')
dataset.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [21]:
DS = fit_cols(dataset,dataset.iloc[:,0:3],Min_Max)
DS = one_hot_cols(DS,['variety'])

DS.head(20)

,sepal.length,sepal.width,petal.length,petal.width,variety_Setosa,variety_Versicolor,variety_Virginica
0,0.222222,0.625000,0.067797,0.2,1,0,0
1,0.166667,0.416667,0.067797,0.2,1,0,0
2,0.111111,0.500000,0.050847,0.2,1,0,0
3,0.083333,0.458333,0.084746,0.2,1,0,0
4,0.194444,0.666667,0.067797,0.2,1,0,0
5,0.305556,0.791667,0.118644,0.4,1,0,0
6,0.083333,0.583333,0.067797,0.3,1,0,0
7,0.194444,0.583333,0.084746,0.2,1,0,0
8,0.027778,0.375000,0.067797,0.2,1,0,0
9,0.166667,0.458333,0.084746,0.1,1,0,0
10,0.305556,0.708333,0.084746,0.2,1,0,0
11,0.138889,0.583333,0.101695,0.2,1,0,0
12,0.138889,0.416667,0.067797,0.1,1,0,0
13,0.000000,0.416667,0.016949,0.1,1,0,0
14,0.416667,0.833333,0.033898,0.2,1,0,0
15,0.388889,1.000000,0.084746,0.4,1,0,0
16,0.305556,0.791667,0.050847,0.4,1,0,0
17,0.222222,0.625000,0.067797,0.3,1,0,0
18,0.388889,0.750000,0.118644,0.3,1,0,0
19,0.222222,0.750000,0.084746,0.3,1,0,0

In [22]:
X_train, X_test, Y_train, Y_test = split_Dataset(DS,['variety_Setosa','variety_Versicolor','variety_Virginica'])
Y_test

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [26]:

import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical



model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])

ModuleNotFoundError: No module named 'tensorflow'

In [24]:


model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])



EPOCH=100
history= model.fit(X_train, Y_train, batch_size=1, epochs=EPOCH,validation_data=(X_test,Y_test))

NameError: name 'model' is not defined

In [25]:

Show_History(history)

NameError: name 'history' is not defined